### PR TITLE
Added code of Kadane's Algorithm in Java

### PR DESCRIPTION
**Pull request by SUCHITRAGIRI**

### CODE REVIEW

**Comment by SUCHITRAGIRI** [comment]
@thet3o @nidhisingh-1 Kindly review it:)

**Review by thet3o — CHANGES_REQUESTED** [review]
You can remove `int n` as parameter, but insert it in the method as `int n = arr.lenght;`, so as to automatically take the length of the array

**Comment by SUCHITRAGIRI** [comment]
@thet3o see now, I did certain changes.

**Review by thet3o — APPROVED** [review]

**Comment by thet3o** [comment]
Nice job!

**Pull request merged**
